spring:
  application:
    name: 'webpost'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webpost
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
          "[format_sql]": true            #SQL 보기 좋게 출력
          "[user_sql_comments]": true     #SQL 생성시 주석 포함
          "[highlight_sql]": true         #SQL 색깔
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop
  jwt:
    secret: "6rVmxOM0O8npkeFQp56K4u7LYrTWXFnxzu2_K3mzOnk"

server:
  port: 8080

